### ISSUE TITLE
Seems like there is a problem in your date field.

### ISSUE THREAD

**Issue by Thrimbda** [TagineerDai/blog#1]
I tried to access your `rss` page but got a 404, it is conspicuous something went wrong.

So I checked travis job log of this repo and found error pasted below:
```bash
ERROR Process failed: _posts/Hello World.md
TypeError: Cannot read property 'offset' of null
    at Object.exports.timezone (/home/travis/build/[secure]/blog/node_modules/hexo/lib/plugins/processor/common.js:44:40)
    at /home/travis/build/[secure]/blog/node_modules/hexo/lib/plugins/processor/post.js:83:42
    at tryCatcher (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/travis/build/[secure]/blog/node_modules/bluebird/js/release/promise.js:638:18)
```
It seems the problem can be located in your timezone config. Plz have a check :)
BTW hexo won't show more detailed date-time than just date(Y-M-D) anyway. why not just remove them= =
and sorry for the misleading example for `date`.

**hope you fix it soon.**

**Comment by TagineerDai** [comment]
Thanks a lot~ 
The timezone setting was changed as you said from `HK` to `Asia/Shanghai` and everything works well now ^ ^
